### ISSUE TITLE
[LetTherBeColors] Color setting breaks bot commands.

### ISSUE THREAD

**Issue by Bass-PHOX** [lenk/aliucord-plugins#12]
Basically, With the plugin enabled, some bots, if not most, bot commands. The bots return an error saying they where unable to understand a value for something that doesn't get displayed. This may cause issues for server staff.

![Screenshot of a Bot failing the command](https://cdn.discordapp.com/attachments/841253022822825994/960872200305520651/unknown.png)
Screenshot of a Bot failing the command.

![Another screenshot of a Bot failing the command](https://cdn.discordapp.com/attachments/841253022822825994/960872919448313956/unknown.png)
Another screenshot of a bot failing the command.

**NOTE:** Screenshots where taken from desktop. All users shown had the plugin enabled with a color value set.

**Comment by lenk** [comment]
didn't add detection for custom bot commands due to Discord forcing bot commands to use / slashes, any bots not following slash formatting are not up to standards 

https://support.discord.com/hc/en-us/articles/1500000368501-Slash-Commands-FAQ
