### ISSUE TITLE
[BetterMarkdown] Cursor and extra letter bug

### ISSUE THREAD

**Issue by WitherredAway** [lenk/aliucord-plugins#4]
When using code-blocks, you can't see select highlight nor the cursor
![IMG_20211231_103116](https://user-images.githubusercontent.com/81734495/147804315-5543a35c-3163-4b73-b9ad-ba0e7e354535.jpg)
(the text is selected)

And in this image, it shouldn't markdown this extra letter (this shows for all markdown afaik)
![IMG_20211231_103207](https://user-images.githubusercontent.com/81734495/147804354-d1042746-fcba-4d42-a92c-34ea023c83a4.jpg)

**Comment by lenk** [comment]
**Fixed on version 1.0.7**

Make sure to update your plugin!

**Comment by WitherredAway** [comment]
thank you, much appreciated!
