### ISSUE TITLE
Let there be colors not ignoring emoji only messages

### ISSUE THREAD

**Issue by BeeFox-sys** [lenk/aliucord-plugins#8]
method: send a message with only emotes (and optionally spaces)

expected result: let there be colours does not add the encoded color to the end of the message

actually result: the encoded color is added to the message, preventing bigmoji

**Comment by lenk** [comment]
What version are you on? This has been fixed ages ago, make sure to update your plugins, current version is v1.0.7

![???](https://c.tenor.com/zw6xPc2NxcQAAAAM/confusedanime.gif)

**Comment by BeeFox-sys** [comment]
i am on 1.0.7

**Comment by BeeFox-sys** [comment]
bigmoji is in a separate message
![Screenshot_2022-01-06-20-53-01-42_fa4ea8e8aeb69dcd3ab969e8fd3d4310](https://user-images.githubusercontent.com/42090331/148364287-01f9f0dc-bb1c-4c41-b966-6bef7c6d503c.jpg)

**Comment by BeeFox-sys** [comment]
and this is with my colour value cleared
![Uploading Screenshot_2022-01-06-20-54-36-52_fa4ea8e8aeb69dcd3ab969e8fd3d4310.jpg…]()

**Comment by BeeFox-sys** [comment]
![Screenshot_2022-01-06-20-54-36-52_fa4ea8e8aeb69dcd3ab969e8fd3d4310](https://user-images.githubusercontent.com/42090331/148364627-7aa079ab-c03d-4b6c-84a3-851b80a77229.jpg)
